name: Rust Static Analysis

on:
  push:
    branches: [ main, 'feat/**', 'fix/**', 'chore/**', 'dependabot/**' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 5'

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    strategy:
      matrix:
        language: [ 'rust' ]

    steps:
      - uses: actions/checkout@v7
      - uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
      - name: Verify Compilation and Lint Using Clippy
        run: |
          cargo clippy
        working-directory: ./rust
      - uses: github/codeql-action/analyze@v4
